# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Relase

on:
  push:
    tags:
      "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Run release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create dirs
      #   run: mkdir -p dist/windows dist/linux dist/darwin

      # - name: Build Linux
      #   env:
      #     GOOS: linux
      #     GOARCH: amd64
      #   run: go build -trimpath -o dist/${GOOS}/quicclient.linux ./...

      # - name: Build Windows
      #   env:
      #     GOOS: windows
      #     GOARCH: 386
      #   run: go build -trimpath -o dist/${GOOS}/quicclient.exe ./...

      # - name: Build Darwin
      #   env:
      #     GOOS: darwin
      #     GOARCH: amd64
      #   run: go build -trimpath -o dist/${GOOS}/quicclient.darwin ./...

      # - name: Shasums
      #   run: |
      #     cd dist
      #     sha256sum */* | tee SHA256SUMS

      # - name: Upload release assets
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       dist/*
      #       dist/*/*
